app:
  host: localhost
  secret_key: 2Jn0DSFN6VBP6hYjA5Xnu92YweMCHDoN
database:
  name: newsletter
  host: localhost
  port: 5432
  username: postgres
  password: password
  require_ssl: false
email:
  sender: noreply@localhost.com
  api_base_url: http://localhost
  api_auth_token: test-auth-token